fastq_files:
  - class: File
    location: data/U5c_CCGTCC_L001_R1_001.fastq.gz
  - class: File
    location: data/U5c_CCGTCC_L001_R2_001.fastq.gz
reference_fasta:
  class: File
  location: data/hs37d5.fa.gz
readgroup: '@RG\tID:H947YADXX\tSM:NA12878\tPL:ILLUMINA'
sample_name: 'U5c_CCGTCC_L001'
